/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import mainPackage.Controller;
import mainPackage.JugadorEntity;
import mainPackage.NullConnectionException;

/**
 *
 * @author enric
 */
public class JugadorsMenu extends javax.swing.JFrame {

    /**
     * Creates new form JugadorsMenu
     */
    public JugadorsMenu() {
        initComponents();
        hidePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llistarJugadorsBTN = new javax.swing.JButton();
        nouJugadorBTN = new javax.swing.JButton();
        editarJugadorBTN = new javax.swing.JButton();
        borrarJugadorBTN = new javax.swing.JButton();
        nouJugadorPanel = new javax.swing.JPanel();
        nouConfirmBTN = new javax.swing.JButton();
        nouMasterToggleBTN = new javax.swing.JToggleButton();
        nouMasterLabel = new javax.swing.JLabel();
        nomNouTextField = new javax.swing.JTextField();
        nomNouLabel = new javax.swing.JLabel();
        editaJugadorPanel = new javax.swing.JPanel();
        editaConfirmBTN = new javax.swing.JButton();
        editaMasterToggleBTN = new javax.swing.JToggleButton();
        editaMasterLabel = new javax.swing.JLabel();
        editaNomTextField = new javax.swing.JTextField();
        editaNomLabel = new javax.swing.JLabel();
        editaSelectorJugador = new javax.swing.JComboBox<>();
        borraJugadorPanel = new javax.swing.JPanel();
        borraConfirmBTN = new javax.swing.JButton();
        borraSelectorJugador = new javax.swing.JComboBox<>();
        borraDescJugadorLabel = new javax.swing.JLabel();
        llistarJugadorsPanel = new javax.swing.JPanel();
        llistarJugadorsScrollPane = new java.awt.ScrollPane();
        llistarJugadorsLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        llistarJugadorsBTN.setText("<html><h3>Llistar Jugadors</h3></html>");
        llistarJugadorsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llistarJugadorsBTNActionPerformed(evt);
            }
        });
        getContentPane().add(llistarJugadorsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 150, 30));

        nouJugadorBTN.setText("<html><h3>Nou Jugador</h3></html>");
        nouJugadorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouJugadorBTNActionPerformed(evt);
            }
        });
        getContentPane().add(nouJugadorBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 30));

        editarJugadorBTN.setText("<html><h3>Editar Jugador</h3></html>");
        editarJugadorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarJugadorBTNActionPerformed(evt);
            }
        });
        getContentPane().add(editarJugadorBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 150, 30));

        borrarJugadorBTN.setText("<html><h3>Borrar Jugador</h3></html>");
        borrarJugadorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarJugadorBTNActionPerformed(evt);
            }
        });
        getContentPane().add(borrarJugadorBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 150, 30));

        nouJugadorPanel.setBackground(new java.awt.Color(153, 153, 255));

        nouConfirmBTN.setText("<html><h4>Comfirma</h4></html>");
        nouConfirmBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nouConfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouConfirmBTNActionPerformed(evt);
            }
        });

        nouMasterToggleBTN.setText("<html><h4>Arbitra</h4></html>");

        nouMasterLabel.setText("<html><h4>Master</h4></html>");

        nomNouLabel.setText("<html><h4>Nom:</h4></html>");

        javax.swing.GroupLayout nouJugadorPanelLayout = new javax.swing.GroupLayout(nouJugadorPanel);
        nouJugadorPanel.setLayout(nouJugadorPanelLayout);
        nouJugadorPanelLayout.setHorizontalGroup(
            nouJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nouJugadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nouJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nouJugadorPanelLayout.createSequentialGroup()
                        .addGroup(nouJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomNouTextField)
                            .addComponent(nouConfirmBTN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nouJugadorPanelLayout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(nouMasterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nouMasterToggleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(nouJugadorPanelLayout.createSequentialGroup()
                        .addComponent(nomNouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        nouJugadorPanelLayout.setVerticalGroup(
            nouJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nouJugadorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomNouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomNouTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nouJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouMasterToggleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nouMasterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nouConfirmBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(nouJugadorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 120));

        editaJugadorPanel.setBackground(new java.awt.Color(153, 153, 255));

        editaConfirmBTN.setText("<html><h4>Comfirma</h4></html>");
        editaConfirmBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editaConfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaConfirmBTNActionPerformed(evt);
            }
        });

        editaMasterToggleBTN.setText("<html><h4>Arbitra</h4></html>");

        editaMasterLabel.setText("<html><h4>Master</h4></html>");

        editaNomTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaNomTextFieldActionPerformed(evt);
            }
        });

        editaNomLabel.setText("<html><h4>Nou Nom:</h4></html>");

        editaSelectorJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaSelectorJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editaJugadorPanelLayout = new javax.swing.GroupLayout(editaJugadorPanel);
        editaJugadorPanel.setLayout(editaJugadorPanelLayout);
        editaJugadorPanelLayout.setHorizontalGroup(
            editaJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editaJugadorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editaJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editaJugadorPanelLayout.createSequentialGroup()
                        .addComponent(editaNomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editaJugadorPanelLayout.createSequentialGroup()
                        .addGroup(editaJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editaSelectorJugador, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editaNomTextField)
                            .addComponent(editaConfirmBTN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editaJugadorPanelLayout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(editaMasterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editaMasterToggleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        editaJugadorPanelLayout.setVerticalGroup(
            editaJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editaJugadorPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(editaSelectorJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editaNomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editaNomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editaJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editaMasterToggleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editaMasterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editaConfirmBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(editaJugadorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 160));

        borraJugadorPanel.setBackground(new java.awt.Color(153, 153, 255));

        borraConfirmBTN.setText("<html><h4>Comfirma</h4></html>");
        borraConfirmBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borraConfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borraConfirmBTNActionPerformed(evt);
            }
        });

        borraSelectorJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borraSelectorJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borraJugadorPanelLayout = new javax.swing.GroupLayout(borraJugadorPanel);
        borraJugadorPanel.setLayout(borraJugadorPanelLayout);
        borraJugadorPanelLayout.setHorizontalGroup(
            borraJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borraJugadorPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(borraJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(borraConfirmBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(borraSelectorJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borraDescJugadorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        borraJugadorPanelLayout.setVerticalGroup(
            borraJugadorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borraJugadorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borraSelectorJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borraDescJugadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borraConfirmBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(borraJugadorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, 130));

        llistarJugadorsPanel.setBackground(new java.awt.Color(153, 153, 255));

        llistarJugadorsLabel.setBackground(new java.awt.Color(153, 153, 255));
        llistarJugadorsLabel.setOpaque(true);
        llistarJugadorsScrollPane.add(llistarJugadorsLabel);

        javax.swing.GroupLayout llistarJugadorsPanelLayout = new javax.swing.GroupLayout(llistarJugadorsPanel);
        llistarJugadorsPanel.setLayout(llistarJugadorsPanelLayout);
        llistarJugadorsPanelLayout.setHorizontalGroup(
            llistarJugadorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llistarJugadorsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        llistarJugadorsPanelLayout.setVerticalGroup(
            llistarJugadorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llistarJugadorsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        getContentPane().add(llistarJugadorsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 150, 230));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugadorsMenu.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llistarJugadorsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llistarJugadorsBTNActionPerformed
        hidePanels();
        llistarJugadorsPanel.setVisible(true);
        Controller.setPlayers();
        ArrayList<JugadorEntity> aJE = Controller.getPlayers();
        String llistaString = "<html>";
        for(int i = 0; i < aJE.size(); i++){
            llistaString += aJE.get(i).toString();
            llistaString += "<br>";
        }
        llistaString += "</html>";
        llistarJugadorsLabel.setText(llistaString);
    }//GEN-LAST:event_llistarJugadorsBTNActionPerformed

    private void nouJugadorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouJugadorBTNActionPerformed
        hidePanels();
        nouJugadorPanel.setVisible(true);
    }//GEN-LAST:event_nouJugadorBTNActionPerformed

    private void editarJugadorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJugadorBTNActionPerformed
        hidePanels();
        editaJugadorPanel.setVisible(true);
        editaSelectorJugador.removeAllItems();
        Controller.setPlayers();
        fillComboBoxWithPlayers(editaSelectorJugador, Controller.getPlayers());
    }//GEN-LAST:event_editarJugadorBTNActionPerformed

    private void borrarJugadorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarJugadorBTNActionPerformed
        hidePanels();
        borraJugadorPanel.setVisible(true);
        borraSelectorJugador.removeAllItems();
        Controller.setPlayers();
        fillComboBoxWithPlayers(borraSelectorJugador, Controller.getPlayers());
    }//GEN-LAST:event_borrarJugadorBTNActionPerformed

    private void nouConfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouConfirmBTNActionPerformed
        JugadorEntity jE = null;
        if (nomNouTextField.getText().equals("") | nomNouTextField.getText() == null) {
            JFrame popUpFrame = new JFrame();
            String msg = "Siusplau, afageix un nom al jugador";
            JOptionPane.showMessageDialog(popUpFrame, msg, "Falta un nom", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jE = new JugadorEntity(nomNouTextField.getText(), nouMasterToggleBTN.isSelected());
            try {
                Controller.getJt().Insert(jE);
                JFrame popUpFrame = new JFrame();
                String msg = "S'ha afegit un nou jugador amb exit";
                JOptionPane.showMessageDialog(popUpFrame, msg, "Jugador afegit", JOptionPane.PLAIN_MESSAGE);
                hidePanels();

            } catch (NullConnectionException ex) {
                Logger.getLogger(JugadorsMenu.class
                        .getName()).log(Level.SEVERE, null, ex);

            } catch (SQLException ex) {
                Logger.getLogger(JugadorsMenu.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_nouConfirmBTNActionPerformed

    private void editaConfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaConfirmBTNActionPerformed
        JugadorEntity jE = Controller.getPlayers().get(editaSelectorJugador.getSelectedIndex());
        JugadorEntity aux = new JugadorEntity(editaNomTextField.getText(), editaMasterToggleBTN.isSelected());
        if (editaNomTextField.getText().equals("") | editaNomTextField.getText() == null) {
            JFrame popUpFrame = new JFrame();
            String msg = "No pots deixar el nom buit";
            JOptionPane.showMessageDialog(popUpFrame, msg, "Falta un nom", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Controller.getJt().update(aux, jE);
                JFrame popUpFrame = new JFrame();
                String msg = "S'ha modificat el jugador amb exit";
                JOptionPane.showMessageDialog(popUpFrame, msg, "Jugador modificat", JOptionPane.PLAIN_MESSAGE);
                hidePanels();

            } catch (NullConnectionException ex) {
                Logger.getLogger(JugadorsMenu.class
                        .getName()).log(Level.SEVERE, null, ex);

            } catch (SQLException ex) {
                Logger.getLogger(JugadorsMenu.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_editaConfirmBTNActionPerformed

    private void editaSelectorJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaSelectorJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editaSelectorJugadorActionPerformed

    private void editaNomTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaNomTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editaNomTextFieldActionPerformed

    private void borraConfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borraConfirmBTNActionPerformed
        JugadorEntity jE = Controller.getPlayers().get(borraSelectorJugador.getSelectedIndex());
        try {
            Controller.getJt().delete(jE);
            JFrame popUpFrame = new JFrame();
            String msg = "S'ha borrat el jugador amb exit";
            JOptionPane.showMessageDialog(popUpFrame, msg, "Jugador borrat", JOptionPane.PLAIN_MESSAGE);
            hidePanels();

        } catch (NullConnectionException ex) {
            Logger.getLogger(JugadorsMenu.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(JugadorsMenu.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_borraConfirmBTNActionPerformed

    private void borraSelectorJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borraSelectorJugadorActionPerformed
        JugadorEntity jE = Controller.getPlayers().get(borraSelectorJugador.getSelectedIndex());
        borraDescJugadorLabel.setText("<html>" + jE.toString() + "</html>");
    }//GEN-LAST:event_borraSelectorJugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton borraConfirmBTN;
    private javax.swing.JLabel borraDescJugadorLabel;
    private javax.swing.JPanel borraJugadorPanel;
    private javax.swing.JComboBox<String> borraSelectorJugador;
    private javax.swing.JButton borrarJugadorBTN;
    private javax.swing.JButton editaConfirmBTN;
    private javax.swing.JPanel editaJugadorPanel;
    private javax.swing.JLabel editaMasterLabel;
    private javax.swing.JToggleButton editaMasterToggleBTN;
    private javax.swing.JLabel editaNomLabel;
    private javax.swing.JTextField editaNomTextField;
    private javax.swing.JComboBox<String> editaSelectorJugador;
    private javax.swing.JButton editarJugadorBTN;
    private javax.swing.JButton llistarJugadorsBTN;
    private javax.swing.JLabel llistarJugadorsLabel;
    private javax.swing.JPanel llistarJugadorsPanel;
    private java.awt.ScrollPane llistarJugadorsScrollPane;
    private javax.swing.JLabel nomNouLabel;
    private javax.swing.JTextField nomNouTextField;
    private javax.swing.JButton nouConfirmBTN;
    private javax.swing.JButton nouJugadorBTN;
    private javax.swing.JPanel nouJugadorPanel;
    private javax.swing.JLabel nouMasterLabel;
    private javax.swing.JToggleButton nouMasterToggleBTN;
    // End of variables declaration//GEN-END:variables

    private void hidePanels() {
        nouJugadorPanel.setVisible(false);
        editaJugadorPanel.setVisible(false);
        borraJugadorPanel.setVisible(false);
        llistarJugadorsPanel.setVisible(false);
    }

    private void fillComboBoxWithPlayers(JComboBox<String> playerSelector, ArrayList<JugadorEntity> players) {

        for (int i = 0; i < players.size(); i++) {
            playerSelector.addItem(players.get(i).getNom());
        }
    }
}
