/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import mainPackage.BDConnection;
import mainPackage.Controller;
import mainPackage.JugadorTable;
import mainPackage.PersonatgeTable;

/**
 *
 * @author enric
 */
public class mainFrame extends javax.swing.JFrame {
    //VARIABLES FOR CONECTION
    
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        personatgesBTN = new javax.swing.JButton();
        jugadorsBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(341, 429));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><h1>Arxiu de Personatges</h1></html>");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 30));

        personatgesBTN.setText("<html><h4>Personatges</h4><html>");
        personatgesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personatgesBTNActionPerformed(evt);
            }
        });
        getContentPane().add(personatgesBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 147, 40));

        jugadorsBTN.setText("<html><h4>Jugadors</h4><html>");
        jugadorsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorsBTNActionPerformed(evt);
            }
        });
        getContentPane().add(jugadorsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 147, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondomenuprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personatgesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personatgesBTNActionPerformed
       if(Controller.getPersonatgesMenu() == null){
           PersonatgesMenu personatgesMenu = new PersonatgesMenu();
           Controller.setPersonatgesMenu(personatgesMenu);
       }
       Controller.getPersonatgesMenu().setVisible(true);
    }//GEN-LAST:event_personatgesBTNActionPerformed

    private void jugadorsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorsBTNActionPerformed
        if(Controller.getJugadorsMenu() == null){
            JugadorsMenu jugadorsMenu = new JugadorsMenu();
            Controller.setJugadorsMenu(jugadorsMenu);
        }
        Controller.getJugadorsMenu().setVisible(true);
    }//GEN-LAST:event_jugadorsBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Controller.connect();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jugadorsBTN;
    private javax.swing.JButton personatgesBTN;
    // End of variables declaration//GEN-END:variables
}
