/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author enric
 */
public class PersonatgesMenu extends javax.swing.JFrame {

    /**
     * Creates new form PersonatgesMenu
     */
    public PersonatgesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        llistaPJBTN = new javax.swing.JButton();
        editaPJBTN = new javax.swing.JButton();
        nouPJBTN = new javax.swing.JButton();
        borraPJBTN = new javax.swing.JButton();
        PersonatgesTitle = new javax.swing.JLabel();
        nouPJPanel = new javax.swing.JPanel();
        NOU_PJ_TEXT01 = new javax.swing.JLabel();
        nouPJSelectorJugador = new javax.swing.JComboBox<>();
        NOU_PJ_TEXT02 = new javax.swing.JLabel();
        nouNomPJTextField = new javax.swing.JTextField();
        NOU_PJ_TEXT03 = new javax.swing.JLabel();
        nouPJSelectorRaza = new javax.swing.JComboBox<>();
        NOU_PJ_TEXT04 = new javax.swing.JLabel();
        nouPJSelectorClasse = new javax.swing.JComboBox<>();
        NOU_PJ_TEXT05 = new javax.swing.JLabel();
        NOU_FUE_TEXT = new javax.swing.JLabel();
        NOU_DES_TEXT = new javax.swing.JLabel();
        NOU_CON_TEXT = new javax.swing.JLabel();
        NOU_INT_TEXT = new javax.swing.JLabel();
        NOU_SAB_TEXT = new javax.swing.JLabel();
        NOU_CAR_TEXT = new javax.swing.JLabel();
        FUEjRadioButton = new javax.swing.JRadioButton();
        DESjRadioButton = new javax.swing.JRadioButton();
        CONjRadioButton = new javax.swing.JRadioButton();
        INTjRadioButton = new javax.swing.JRadioButton();
        SABjRadioButton = new javax.swing.JRadioButton();
        CARjRadioButton = new javax.swing.JRadioButton();
        nouFUEPunt = new javax.swing.JLabel();
        nouDESPunt = new javax.swing.JLabel();
        nouCONPunt = new javax.swing.JLabel();
        nouINTPunt = new javax.swing.JLabel();
        nouSABPunt = new javax.swing.JLabel();
        nouCARPunt = new javax.swing.JLabel();
        addPunt = new javax.swing.JButton();
        removePunt = new javax.swing.JButton();
        nouPuntuacionsSelector = new javax.swing.JComboBox<>();
        NOU_PJ_TEXT06 = new javax.swing.JLabel();
        nouPJConfirmBTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PersonatgesBackground = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        llistaPJBTN.setText("<html><h3>Llista Personatges</h3></html>");
        getContentPane().add(llistaPJBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 160, 40));

        editaPJBTN.setText("<html><h3>Edita Personatge</h3></html>");
        getContentPane().add(editaPJBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 40));

        nouPJBTN.setText("<html><h3>Nou Personatge</h3></html>");
        getContentPane().add(nouPJBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 40));

        borraPJBTN.setText("<html><h3>Borra Personatge</h3></html>");
        getContentPane().add(borraPJBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, 40));

        PersonatgesTitle.setForeground(new java.awt.Color(255, 255, 255));
        PersonatgesTitle.setText("<html><h1>Fitxes de Personatge</h1></html>");
        getContentPane().add(PersonatgesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        nouPJPanel.setOpaque(false);
        nouPJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOU_PJ_TEXT01.setForeground(new java.awt.Color(0, 255, 0));
        NOU_PJ_TEXT01.setText("<html><p>Selecciona un jugador:</p></html>");
        nouPJPanel.add(NOU_PJ_TEXT01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 22));

        nouPJPanel.add(nouPJSelectorJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, -1));

        NOU_PJ_TEXT02.setForeground(new java.awt.Color(51, 255, 51));
        NOU_PJ_TEXT02.setText("<html><p>Nom:</p></html>");
        nouPJPanel.add(NOU_PJ_TEXT02, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 51, -1, 20));
        nouPJPanel.add(nouNomPJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 51, 170, -1));

        NOU_PJ_TEXT03.setForeground(new java.awt.Color(0, 255, 0));
        NOU_PJ_TEXT03.setText("<html><p>Raça:</p></html>");
        nouPJPanel.add(NOU_PJ_TEXT03, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 89, -1, 20));

        nouPJPanel.add(nouPJSelectorRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 89, 110, -1));

        NOU_PJ_TEXT04.setForeground(new java.awt.Color(0, 255, 0));
        NOU_PJ_TEXT04.setText("<html><p>Classe:</p></html>");
        nouPJPanel.add(NOU_PJ_TEXT04, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 127, -1, 20));

        nouPJPanel.add(nouPJSelectorClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 127, 110, -1));

        NOU_PJ_TEXT05.setForeground(new java.awt.Color(204, 204, 204));
        NOU_PJ_TEXT05.setText("<html><h3>Atributs</h3></html>");
        nouPJPanel.add(NOU_PJ_TEXT05, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 165, -1, 28));

        NOU_FUE_TEXT.setForeground(new java.awt.Color(204, 204, 204));
        NOU_FUE_TEXT.setText("<html><h4>FUE</h4></html>");
        nouPJPanel.add(NOU_FUE_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 211, 24, 22));

        NOU_DES_TEXT.setForeground(new java.awt.Color(204, 204, 204));
        NOU_DES_TEXT.setText("<html><h4>DES</h4></html>");
        nouPJPanel.add(NOU_DES_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 239, -1, 22));

        NOU_CON_TEXT.setForeground(new java.awt.Color(204, 204, 204));
        NOU_CON_TEXT.setText("<html><h4>CON</h4></html>");
        nouPJPanel.add(NOU_CON_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 22));

        NOU_INT_TEXT.setForeground(new java.awt.Color(204, 204, 204));
        NOU_INT_TEXT.setText("<html><h4>INT</h4></html>");
        nouPJPanel.add(NOU_INT_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 25, 22));

        NOU_SAB_TEXT.setForeground(new java.awt.Color(204, 204, 204));
        NOU_SAB_TEXT.setText("<html><h4>SAB</h4></html>");
        nouPJPanel.add(NOU_SAB_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 22));

        NOU_CAR_TEXT.setForeground(new java.awt.Color(204, 204, 204));
        NOU_CAR_TEXT.setText("<html><h4>CAR</h4></html>");
        nouPJPanel.add(NOU_CAR_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 22));

        buttonGroup1.add(FUEjRadioButton);
        FUEjRadioButton.setOpaque(false);
        nouPJPanel.add(FUEjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, -1, -1));

        buttonGroup1.add(DESjRadioButton);
        DESjRadioButton.setOpaque(false);
        nouPJPanel.add(DESjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, -1, -1));

        buttonGroup1.add(CONjRadioButton);
        CONjRadioButton.setOpaque(false);
        nouPJPanel.add(CONjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        buttonGroup1.add(INTjRadioButton);
        INTjRadioButton.setOpaque(false);
        nouPJPanel.add(INTjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        buttonGroup1.add(SABjRadioButton);
        SABjRadioButton.setOpaque(false);
        nouPJPanel.add(SABjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        buttonGroup1.add(CARjRadioButton);
        CARjRadioButton.setOpaque(false);
        nouPJPanel.add(CARjRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        nouFUEPunt.setForeground(new java.awt.Color(204, 204, 204));
        nouFUEPunt.setText("0");
        nouPJPanel.add(nouFUEPunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        nouDESPunt.setForeground(new java.awt.Color(204, 204, 204));
        nouDESPunt.setText("0");
        nouPJPanel.add(nouDESPunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        nouCONPunt.setForeground(new java.awt.Color(204, 204, 204));
        nouCONPunt.setText("0");
        nouPJPanel.add(nouCONPunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 7, -1));

        nouINTPunt.setForeground(new java.awt.Color(204, 204, 204));
        nouINTPunt.setText("0");
        nouPJPanel.add(nouINTPunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        nouSABPunt.setForeground(new java.awt.Color(204, 204, 204));
        nouSABPunt.setText("0");
        nouPJPanel.add(nouSABPunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 10, -1));

        nouCARPunt.setForeground(new java.awt.Color(204, 204, 204));
        nouCARPunt.setText("0");
        nouPJPanel.add(nouCARPunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        addPunt.setText("<html><h3>&lt&lt</h3></html>");
        nouPJPanel.add(addPunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 26));

        removePunt.setText("<html><h3>&gt&gt</h3></html>");
        nouPJPanel.add(removePunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, 26));

        nouPJPanel.add(nouPuntuacionsSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 70, -1));

        NOU_PJ_TEXT06.setForeground(new java.awt.Color(204, 204, 204));
        NOU_PJ_TEXT06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOU_PJ_TEXT06.setText("<html><h4>Puntuacions</h4></html>");
        nouPJPanel.add(NOU_PJ_TEXT06, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, 22));

        nouPJConfirmBTN.setText("<html><h3>CREA</h3></html>");
        nouPJPanel.add(nouPJConfirmBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, 50));

        jButton1.setText("<html><h5>Re-Roll</h5></html>");
        nouPJPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 70, 20));

        getContentPane().add(nouPJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 330, 420));

        PersonatgesBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/personatges.menu.jpg"))); // NOI18N
        getContentPane().add(PersonatgesBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CARjRadioButton;
    private javax.swing.JRadioButton CONjRadioButton;
    private javax.swing.JRadioButton DESjRadioButton;
    private javax.swing.JRadioButton FUEjRadioButton;
    private javax.swing.JRadioButton INTjRadioButton;
    private javax.swing.JLabel NOU_CAR_TEXT;
    private javax.swing.JLabel NOU_CON_TEXT;
    private javax.swing.JLabel NOU_DES_TEXT;
    private javax.swing.JLabel NOU_FUE_TEXT;
    private javax.swing.JLabel NOU_INT_TEXT;
    private javax.swing.JLabel NOU_PJ_TEXT01;
    private javax.swing.JLabel NOU_PJ_TEXT02;
    private javax.swing.JLabel NOU_PJ_TEXT03;
    private javax.swing.JLabel NOU_PJ_TEXT04;
    private javax.swing.JLabel NOU_PJ_TEXT05;
    private javax.swing.JLabel NOU_PJ_TEXT06;
    private javax.swing.JLabel NOU_SAB_TEXT;
    private javax.swing.JLabel PersonatgesBackground;
    private javax.swing.JLabel PersonatgesTitle;
    private javax.swing.JRadioButton SABjRadioButton;
    private javax.swing.JButton addPunt;
    private javax.swing.JButton borraPJBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton editaPJBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton llistaPJBTN;
    private javax.swing.JLabel nouCARPunt;
    private javax.swing.JLabel nouCONPunt;
    private javax.swing.JLabel nouDESPunt;
    private javax.swing.JLabel nouFUEPunt;
    private javax.swing.JLabel nouINTPunt;
    private javax.swing.JTextField nouNomPJTextField;
    private javax.swing.JButton nouPJBTN;
    private javax.swing.JButton nouPJConfirmBTN;
    private javax.swing.JPanel nouPJPanel;
    private javax.swing.JComboBox<String> nouPJSelectorClasse;
    private javax.swing.JComboBox<String> nouPJSelectorJugador;
    private javax.swing.JComboBox<String> nouPJSelectorRaza;
    private javax.swing.JComboBox<String> nouPuntuacionsSelector;
    private javax.swing.JLabel nouSABPunt;
    private javax.swing.JButton removePunt;
    // End of variables declaration//GEN-END:variables
}
